### ISSUE TITLE
Released today and old users don't have access

### ISSUE THREAD

**Issue by malekamiri** [codykerns/PurchasesHelper#10]
I just released today and it did not work, let me know if you see anything wrong.
All my previous versions had builds between 1 and 4.

In AppDelegate:
```
Purchases.configure(withAPIKey: "KEY")

CompatibilityAccessManager.shared.register(entitlement:
                                            .init(entitlement: "Premium", versions: ["1", "2", "3", "4"])
)
```

In ViewDidLoad:

```
CompatibilityAccessManager.shared.isActive(entitlement: "Premium") { (isActive, purchaserInfo) in
        if isActive {
            UserDefaults.standard.set(true, forKey: "purchased")
        } else {
            UserDefaults.standard.set(false, forKey: "purchased")
        }
}
```

It works when I use 'sandboxVersionOverride" in testing.

I stopped the phased release of the version but not sure what to do now
thanks

**Comment by malekamiri** [comment]
I think the register function takes some time to be processed after I call it in appDelegate and is not finished processing when I call isActive in viewDidLoad.

**Comment by SwapnanilDhol** [comment]
Hello, I am having this issue as well. Were you able to fix it?

**Comment by codykerns** [comment]
This is likely an issue with the versions you registered, or that you aren't syncing purchases before checking if the user has access to the entitlement.

It looks like you're only calling `register`, and not `configure`, so you aren't syncing a user's receipt by default. In which case, isActive is false because there is no originalApplicationVersion for CompatibilityAccessManager to reference when checking if the user should have access. Try syncing a receipt by calling `Purchases.shared.syncPurchases`, or by changing your initialization code to use `configure` instead of `register`.

I'm going to close this out, but feel free to follow up if you have additional questions.
